<<<<<<< HEAD
// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

    int N = Integer.parseInt(args[0]);

		int countLessEqual = 0;
		int countGratest = 0;

        for (int i = 0; i < N; i++) {
		double r = Math.random();
		if (r > 0.5) {
			countGratest++;
		}
		else // r <= 0.5
		countLessEqual++;
	}
       System.out.println("> 0.5: " + countGratest + " times");
        System.out.println("<= 0.5: " + countLessEqual + " times");
		

	}
	}

// Great Namings :)



=======
// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Replace this comment with your code
	}
}
>>>>>>> f5de349671672dfb71c17b605b2edaaaaacd06a6
